// Code generated by go-bindata.
// sources:
// ui/dist/311f9ffb736bec3f5d942707f570ed68.eot
// ui/dist/485d934dff5213b0dafdc757c1a4127c.eot
// ui/dist/4f5c35f76f22fbdeb718c79aeec7f274.woff
// ui/dist/bundle.js
// ui/dist/c277c90fab96566a2f3aca9b9a0316d8.woff
// ui/dist/cc21326e8e182de2ae065bd3057c20e5.ttf
// ui/dist/eeeeeaf16a26c17e07497e90778d3312.ttf
// ui/dist/index.html
// DO NOT EDIT!

package app

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// uiDist311f9ffb736bec3f5d942707f570ed68Eot reads file data from disk. It returns an error on failure.
func uiDist311f9ffb736bec3f5d942707f570ed68Eot() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/311f9ffb736bec3f5d942707f570ed68.eot")
	name := "ui/dist/311f9ffb736bec3f5d942707f570ed68.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDist485d934dff5213b0dafdc757c1a4127cEot reads file data from disk. It returns an error on failure.
func uiDist485d934dff5213b0dafdc757c1a4127cEot() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/485d934dff5213b0dafdc757c1a4127c.eot")
	name := "ui/dist/485d934dff5213b0dafdc757c1a4127c.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDist4f5c35f76f22fbdeb718c79aeec7f274Woff reads file data from disk. It returns an error on failure.
func uiDist4f5c35f76f22fbdeb718c79aeec7f274Woff() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/4f5c35f76f22fbdeb718c79aeec7f274.woff")
	name := "ui/dist/4f5c35f76f22fbdeb718c79aeec7f274.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDistBundleJs reads file data from disk. It returns an error on failure.
func uiDistBundleJs() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/bundle.js")
	name := "ui/dist/bundle.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDistC277c90fab96566a2f3aca9b9a0316d8Woff reads file data from disk. It returns an error on failure.
func uiDistC277c90fab96566a2f3aca9b9a0316d8Woff() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/c277c90fab96566a2f3aca9b9a0316d8.woff")
	name := "ui/dist/c277c90fab96566a2f3aca9b9a0316d8.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDistCc21326e8e182de2ae065bd3057c20e5Ttf reads file data from disk. It returns an error on failure.
func uiDistCc21326e8e182de2ae065bd3057c20e5Ttf() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/cc21326e8e182de2ae065bd3057c20e5.ttf")
	name := "ui/dist/cc21326e8e182de2ae065bd3057c20e5.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDistEeeeeaf16a26c17e07497e90778d3312Ttf reads file data from disk. It returns an error on failure.
func uiDistEeeeeaf16a26c17e07497e90778d3312Ttf() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/eeeeeaf16a26c17e07497e90778d3312.ttf")
	name := "ui/dist/eeeeeaf16a26c17e07497e90778d3312.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// uiDistIndexHtml reads file data from disk. It returns an error on failure.
func uiDistIndexHtml() (*asset, error) {
	path := filepath.Join(rootDir, "ui/dist/index.html")
	name := "ui/dist/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"ui/dist/311f9ffb736bec3f5d942707f570ed68.eot": uiDist311f9ffb736bec3f5d942707f570ed68Eot,
	"ui/dist/485d934dff5213b0dafdc757c1a4127c.eot": uiDist485d934dff5213b0dafdc757c1a4127cEot,
	"ui/dist/4f5c35f76f22fbdeb718c79aeec7f274.woff": uiDist4f5c35f76f22fbdeb718c79aeec7f274Woff,
	"ui/dist/bundle.js": uiDistBundleJs,
	"ui/dist/c277c90fab96566a2f3aca9b9a0316d8.woff": uiDistC277c90fab96566a2f3aca9b9a0316d8Woff,
	"ui/dist/cc21326e8e182de2ae065bd3057c20e5.ttf": uiDistCc21326e8e182de2ae065bd3057c20e5Ttf,
	"ui/dist/eeeeeaf16a26c17e07497e90778d3312.ttf": uiDistEeeeeaf16a26c17e07497e90778d3312Ttf,
	"ui/dist/index.html": uiDistIndexHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"ui": &bintree{nil, map[string]*bintree{
		"dist": &bintree{nil, map[string]*bintree{
			"311f9ffb736bec3f5d942707f570ed68.eot": &bintree{uiDist311f9ffb736bec3f5d942707f570ed68Eot, map[string]*bintree{}},
			"485d934dff5213b0dafdc757c1a4127c.eot": &bintree{uiDist485d934dff5213b0dafdc757c1a4127cEot, map[string]*bintree{}},
			"4f5c35f76f22fbdeb718c79aeec7f274.woff": &bintree{uiDist4f5c35f76f22fbdeb718c79aeec7f274Woff, map[string]*bintree{}},
			"bundle.js": &bintree{uiDistBundleJs, map[string]*bintree{}},
			"c277c90fab96566a2f3aca9b9a0316d8.woff": &bintree{uiDistC277c90fab96566a2f3aca9b9a0316d8Woff, map[string]*bintree{}},
			"cc21326e8e182de2ae065bd3057c20e5.ttf": &bintree{uiDistCc21326e8e182de2ae065bd3057c20e5Ttf, map[string]*bintree{}},
			"eeeeeaf16a26c17e07497e90778d3312.ttf": &bintree{uiDistEeeeeaf16a26c17e07497e90778d3312Ttf, map[string]*bintree{}},
			"index.html": &bintree{uiDistIndexHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

